CS50W/three/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),  # "/hello" route to run index function in views
    path("joe", views.joe, name="joe"),  # "/hello/joe" route to run joe function in views
    path("<str:name>", views.greet, name="greet")
]

CS50W/three/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),  #default route function in views.py
]

CS50W/three/task/urls.py
from django.urls import path

from . import views

app_name = "task"
urlpatterns = [
    path("", views.index, name="index"),  #default route function in views.py
    path("add", views.add, name="add"),
]

CS50W/three/three/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),  #goto hello project
    path("newyear/", include("newyear.urls")),  #goto newyear urls.py
    path("task/", include("task.urls"))  #goto task urls.py
]

CS50W/three/hello/models.py
from django.db import models

# Create your models here.

CS50W/three/newyear/models.py
from django.db import models

# Create your models here.

CS50W/three/task/models.py
from django.db import models

# Create your models here.

CS50W/three/hello/views.py
import re
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "hello/index.html")  # in template/hello/index.html


def joe(request):
    return HttpResponse(request, "Hello, Joe!")


def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize(),
    })

CS50W/three/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.


def index(request):
    now = datetime.datetime.now()
    # must in template fold /template/newyear/index.html
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1,
    })

CS50W/three/task/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    #priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)


def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "task/index.html", {"tasks": request.session["tasks"]})


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            #tasks.append(task)
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("task:index"))  #task:index != task/index
        else:
            return render(request, "task/add.html", {"form": form})

    return render(request, "task/add.html", {"form": NewTaskForm()})

CS50W/three/hello/templates/hello/greet.html
<!DOCTYPE html>
<html>
    <head>
        <title>Web</title>
    </head>
    <body>
        <h1>Greet, {{name}}!</h1>
    </body>
</html>

CS50W/three/hello/templates/hello/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>web</title>
    </head>
    <body>
        <h1>Hello, world!</h1>
    </body>
</html>

CS50W/three/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it New Year?</title>
        <link href="{% static 'newyear/style.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% if newyear %}
        <!-- condition in django -->
        <h1>YES</h1>
        {% else %}
        <h1>NO</h1>
        {% endif %}
    </body>
</html>

CS50W/three/task/templates/task/add.html
{% extends 'task/layout.html' %} {% block body %}

<h1>Add tasks</h1>
<form action="{% url 'task:add' %}" method="post">
    {% csrf_token %} {{ form }}
    <input type="submit" />
</form>
<a href="{% url 'task:index' %}">View Tasks</a>

{% endblock %}

CS50W/three/task/templates/task/index.html
{% extends 'task/layout.html' %} {% block body %}
<h1>Tasks</h1>
<ul>
    {% for task in tasks %}
    <li>{{ task }}</li>
    {% empty %}
    <li>No task.</li>
    {% endfor %}
</ul>
<a href="{% url 'task:add' %}">Add a new task</a>
<!-- urls.py name = add -->
{% endblock %}

CS50W/three/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body%} {% endblock %}
    </body>
</html>